<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>RsMcpServer.Web</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.5" />
        <PackageReference Include="Microsoft.Extensions.AI" Version="10.2.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
        <PackageReference Include="ModelContextProtocolServer.Sse" Version="0.4.0" />
        <PackageReference Include="OpenAPISwaggerUI" Version="9.2024.1215.2209" />
    </ItemGroup>

    <ItemGroup>
            <ProjectReference Include="..\..\RSChatApp.ReportServer\ReportServer.Abstraction\ReportServer.Abstraction.csproj" />
            <ProjectReference Include="..\..\RSChatApp.ReportServer\ReportServer.RpcClient\ReportServer.RpcClient.csproj" />
            <ProjectReference Include="..\..\RSChatApp.Common\RSChatApp.Common.ServiceDefaults\RSChatApp.Common.ServiceDefaults.csproj" />
            <ProjectReference Include="..\..\RSChatApp.RSChatApp\RSChatApp.Shared.Infrastructure.Mcp\RSChatApp.Shared.Infrastructure.Mcp.csproj" />
            <ProjectReference Include="..\RsMcpServer.Identity\RsMcpServer.Identity.csproj" />
    </ItemGroup>

</Project>
