<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>RSChatApp.Infrastructure</RootNamespace>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Polly.Core" Version="8.6.5" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.0" />
        <PackageReference Include="ModelContextProtocol.Core" Version="0.3.0-preview.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\RSChatApp.Common\RSChatApp.Common\RSChatApp.Common.csproj" />
      <ProjectReference Include="..\..\RSChatApp.ReportServer\ReportServer.Abstraction\ReportServer.Abstraction.csproj" />
      <ProjectReference Include="..\RSChatApp.Shared.Infrastructure.Mcp\RSChatApp.Shared.Infrastructure.Mcp.csproj" />
    </ItemGroup>

</Project>
