<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="LazyCache" Version="2.4.0" />
      <PackageReference Include="LazyCache.AspNetCore" Version="2.4.0" />
      <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
      <PackageReference Include="Microsoft.Extensions.AI" Version="10.3.0" />
      <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.3.0" />
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.8" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.8" />
      <PackageReference Include="Microsoft.Playwright" Version="1.57.0" />
      <PackageReference Include="Microsoft.SemanticKernel" Version="1.72.0" />
      <PackageReference Include="Microsoft.SemanticKernel.Connectors.Qdrant" Version="1.72.0-preview" />
      <PackageReference Include="Microsoft.SemanticKernel.Core" Version="1.72.0" />
      <PackageReference Include="ModelContextProtocol" Version="1.0.0" />
      <PackageReference Include="PdfPig" Version="0.1.10" />
      <PackageReference Include="SkiaSharp" Version="3.116.1" />
      <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.116.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\RSChatApp.ReportServer\ReportServer.Abstraction\ReportServer.Abstraction.csproj" />
      <ProjectReference Include="..\..\RSChatApp.RsMcpServer\RsMcpServer.Identity\RsMcpServer.Identity.csproj" />
    </ItemGroup>

</Project>
