<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>196f25f8-2d71-4174-8177-ee76e447db47</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BlazorMonaco" Version="3.4.0" />
    <PackageReference Include="CommunityToolkit.Aspire.OllamaSharp" Version="13.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.0" />
    <PackageReference Include="ModelContextProtocol-SemanticKernel" Version="0.3.0" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="0.3.0-preview.3" />
    <PackageReference Include="ModelContextProtocolServer.Sse" Version="0.4.0" />
    <PackageReference Include="OllamaSharp" Version="5.4.18" />
    <PackageReference Include="System.Linq.Async" Version="6.0.3" />
    <PackageReference Include="Aspire.Qdrant.Client" Version="9.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RSChatApp.Infrastructure\RSChatApp.Infrastructure.csproj" />
    <ProjectReference Include="..\RSChatApp.Shared.Infrastructure.Mcp\RSChatApp.Shared.Infrastructure.Mcp.csproj" />
    <ProjectReference Include="..\..\RSChatApp.Common\RSChatApp.Common.ServiceDefaults\RSChatApp.Common.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\RSChatApp.RsMcpServer\RsMcpServer.Identity\RsMcpServer.Identity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Filter\" />
    <Folder Include="Logs\" />
    <Folder Include="wwwroot\Data\" />
    <Folder Include="Prompts\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Prompts\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Components\Pages\Chat\ToolCalls\ChatCitation.razor" />
  </ItemGroup>

</Project>
